[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
build_unflags =
    -std=gnu++11
lib_deps =
    https://github.com/ESPressio-Development-Platform/EDP-Threading.git#main
    https://github.com/ESPressio-Development-Platform/EDP-System.git#main
    https://github.com/ESPressio-Development-Platform/EDP-Clock.git#main
    https://github.com/ESPressio-Development-Platform/EDP-Platform.git#main
    https://github.com/ESPressio-Development-Platform/EDP-Platform-Portable.git#main
    https://github.com/ESPressio-Development-Platform/EDP-Platform-FreeRTOS.git#main
